### ISSUE TITLE
dr客户端关闭后再次打开报错

### ISSUE THREAD

**Issue by conquer001** [drcoms/drcom-generic#13]
Traceback (most recent call last):
  File "latest-wired.py", line 32, in <module>
    s.bind(("0.0.0.0", 61440))
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use

**Comment by conquer001** [comment]
d版使用的端口为61440  使用lsof -i:61440 查看占用该端口的进程及pid
kill pid
重启程序即可
