### ISSUE TITLE
运行测试脚本，报错

### ISSUE THREAD

**Issue by ksn-cn** [drcoms/drcom-generic#16]
Traceback (most recent call last):
  File "latest-wired.py", line 34, in <module>
    s.bind(("0.0.0.0", 61440))
  File "D:\Program Files\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10048] 通常每个套接字地址(协议/网络地址/端口)

**Comment by ly0** [comment]
是否已经打开了官方客户端？

**Comment by ksn-cn** [comment]
关闭了官方客户端，后运行的脚本

**Comment by ksn-cn** [comment]
是不要完全关闭官方客户端？

**Comment by ksn-cn** [comment]
完全关闭Drcom客户端后，运行报错

Traceback (most recent call last):
  File "latest-wired.py", line 352, in <module>
    main()
  File "latest-wired.py", line 338, in main
    daemon()
  File "latest-wired.py", line 333, in daemon
    with open('/var/run/jludrcom.pid','w') as f:
IOError: [Errno 2] No such file or directory: '/var/run/jludrcom.pid'

**Comment by wodegit** [comment]
我是完整运行了一遍客户端

**Comment by ly0** [comment]
https://github.com/drcoms/drcom-generic/wiki/d%E7%89%88%E7%AE%80%E7%95%A5%E4%BD%BF%E7%94%A8%E5%92%8C%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

    如果是用作在PC上测试，覆盖 latest-wired.py 中从 # CONFIG 到 # CONFIG_END 中间的部分，然后修改 IS_TEST = False 为 IS_TEST = True， 注意自行修改 password 的值。
