### ISSUE TITLE
5.2D版出现socket.timeout: timed out错误

### ISSUE THREAD

**Issue by chih7** [drcoms/drcom-generic#165]
**之前用的挺好的**，昨天开始出现下面的错误
```
[keep-alive2] send3 070228000b031d002f12000000000000a8a8000000000000000000000a08ce8d0000000000000000
Traceback (most recent call last):
  File "./latest-wired.py", line 453, in <module>
    main()
  File "./latest-wired.py", line 451, in main
    keep_alive2(SALT,package_tail,password,server)
  File "./latest-wired.py", line 207, in keep_alive2
    data, address = s.recvfrom(1024)
socket.timeout: timed out
```
脚本无论在openwrt下还是Linux桌面上都会异常退出，但是在windows下用官方客户端没有问题。

附全部日志
[https://gist.github.com/chih7/1d49436de6679234276327d9b3c320e7](https://gist.github.com/chih7/1d49436de6679234276327d9b3c320e7)

出错代码上下文
```
    ran += random.randint(1,10)   
    packet = keep_alive_package_builder(svr_num,dump(ran),tail,3,False)
    log('[keep-alive2] send3',packet.encode('hex'))
    s.sendto(packet, (svr, 61440))
    while True:
        data, address = s.recvfrom(1024)
        print data
        print address
        if data[0] == '\x07':
            svr_num = svr_num + 1
            break
        else:
            log('[keep-alive2] recv3/unexpected',data.encode('hex'))
```

**Comment by ly0** [comment]
```
KEEP_ALIVE_VERSION = '\xdc\x02'
```

检查这个值是否有变化

**Comment by chih7** [comment]
我重新抓包解析后发现`KEEP_ALIVE_VERSION`的确改变了，更改后可以脚本可以正常运行。
