### ISSUE TITLE
5.2.0x版，电脑跑能上，路由器出现问题

### ISSUE THREAD

**Issue by mowesan** [drcoms/drcom-generic#180]
电脑latest-wired.py配合mentohust能上网，路由器手动启动出现这样的情况
Traceback (most recent call last):
  File "/usr/bin/main.py", line 22, in <module>
    auth = eapauth.EAPAuth(user_info, success_handler=drcom.main)
  File "/usr/bin/eapauth.py", line 33, in __init__
    self.client.bind((login_info['ethernet_interface'], ETHERTYPE_PAE))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device

**Comment by mchome** [comment]
路由器latest-wired.py配合路由器的mentohust
