### ISSUE TITLE
极路由1S官方1.5固件，drcom5.2.0.（P）在线一段时间后断线。

### ISSUE THREAD

**Issue by madman43** [drcoms/drcom-generic#207]
学校：四川天一学院
drcom 版本：5.2.0（P）
已设置99-drcom 和后台自启，断线会自动重拨。

以下是拨号日志
```
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]: Send PPPOE Discovery V1T1 PADI session 0x0 length 12
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]:  dst ff:ff:ff:ff:ff:ff  src d4:ee:7:4a:cd:a3
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]:  [service-name] [host-uniq  a3 05 00 00]
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]: Recv PPPOE Discovery V1T1 PADO session 0x0 length 31
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]:  dst d4:ee:7:4a:cd:a3  src 54:89:98:3d:60:4f
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]:  [service-name] [host-uniq  a3 05 00 00] [AC-name SCDY-MZ-ME60-B1]
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]: Send PPPOE Discovery V1T1 PADR session 0x0 length 12
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]:  dst 54:89:98:3d:60:4f  src d4:ee:7:4a:cd:a3
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]:  [service-name] [host-uniq  a3 05 00 00]
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]: Recv PPPOE Discovery V1T1 PADS session 0x8283 length 12
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]:  dst d4:ee:7:4a:cd:a3  src 54:89:98:3d:60:4f
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]:  [service-name] [host-uniq  a3 05 00 00]
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]: PADS: Service-Name: ''
2017-04-19T18:24:48 Hiwifi daemon.info pppd[1443]: PPP session is 33411
2017-04-19T18:24:48 Hiwifi daemon.warn pppd[1443]: Connected to 54:89:98:3d:60:4f via interface eth2.2
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]: using channel 5
2017-04-19T18:24:48 Hiwifi daemon.info pppd[1443]: Using interface pppoe-wan
2017-04-19T18:24:48 Hiwifi daemon.notice pppd[1443]: Connect: pppoe-wan <--> eth2.2
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]: sent [LCP ConfReq id=0x5 <mru 1480> <magic 0xea35cb27>]
2017-04-19T18:24:48 Hiwifi daemon.debug pppd[1443]: rcvd [LCP ConfAck id=0x5 <mru 1480> <magic 0xea35cb27>]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: rcvd [LCP ConfReq id=0x2 <mru 1492> <auth chap MD5> <magic 0xbc5eeef7>]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: sent [LCP ConfAck id=0x2 <mru 1492> <auth chap MD5> <magic 0xbc5eeef7>]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: sent [LCP EchoReq id=0x0 magic=0xea35cb27]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: rcvd [CHAP Challenge id=0x1 <c6e0fc2a99313396ac8938d47ec27bd8>, name = "Huawei"]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: sent [CHAP Response id=0x1 <c5803eb3c1960efcdf66316eb3138e93>, name = "\r\n083802180329"]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: rcvd [LCP EchoRep id=0x0 magic=0xbc5eeef7]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: rcvd [CHAP Success id=0x1 "Welcome to Drcom System:1310131831"]
2017-04-19T18:24:51 Hiwifi daemon.info pppd[1443]: CHAP authentication succeeded: Welcome to Drcom System:1310131831
2017-04-19T18:24:51 Hiwifi daemon.notice pppd[1443]: CHAP authentication succeeded
2017-04-19T18:24:51 Hiwifi daemon.notice pppd[1443]: peer from calling number 54:89:98:3D:60:4F authorized
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: sent [IPCP ConfReq id=0x9 <addr 0.0.0.0> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: rcvd [IPCP ConfReq id=0x1 <addr 112.195.192.1>]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: sent [IPCP ConfAck id=0x1 <addr 112.195.192.1>]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: rcvd [IPCP ConfNak id=0x9 <addr 112.195.193.146> <ms-dns1 119.6.6.6> <ms-dns2 114.114.114.114>]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: sent [IPCP ConfReq id=0xa <addr 112.195.193.146> <ms-dns1 119.6.6.6> <ms-dns2 114.114.114.114>]
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: rcvd [IPCP ConfAck id=0xa <addr 112.195.193.146> <ms-dns1 119.6.6.6> <ms-dns2 114.114.114.114>]
2017-04-19T18:24:51 Hiwifi daemon.notice pppd[1443]: local  IP address 112.195.193.146
2017-04-19T18:24:51 Hiwifi daemon.notice pppd[1443]: remote IP address 112.195.192.1
2017-04-19T18:24:51 Hiwifi daemon.notice pppd[1443]: primary   DNS address 119.6.6.6
2017-04-19T18:24:51 Hiwifi daemon.notice pppd[1443]: secondary DNS address 114.114.114.114
2017-04-19T18:24:51 Hiwifi daemon.debug pppd[1443]: Script /lib/netifd/ppp-up started (pid 540)
2017-04-19T18:24:52 Hiwifi daemon.debug pppd[1443]: Script /lib/netifd/ppp-up finished (pid 540), status = 0x0
```

**Comment by ly0** [comment]
drcom的脚本日志呢？

**Comment by madman43** [comment]
auth svr: 119.6.23.78
pppoe_flag: 24
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
只有这点

**Comment by ly0** [comment]
呃，这么点日志说明没心跳成功，检查一下拨号成功以后认证网关是不是通的

**Comment by madman43** [comment]
我把IS_TEST=改成了True之后就有以下内容
但是输入ps之后就看不见drcom在运行了
auth svr: 119.6.23.78
pppoe_flag: 24
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000ed6a5615770745b5a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000770745b500620024ed6a5615d1203dc7780babe700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000096b5615770745b5a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000770745b500620024096b5615bb79d04642e2323800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000256b5615770745b5a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:070260000300000000000000770745b500620024256b561546f54860dc3fbfaa00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000426b5615770745b5a8a80000e659f16700000000dc020000
auth svr: 119.6.23.78
pppoe_flag: 24
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
auth svr: 119.6.23.78
pppoe_flag: 24
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
auth svr: 119.6.23.78
pppoe_flag: 24
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
auth svr: 119.6.23.78
pppoe_flag: 24
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
auth svr: 119.6.23.78
pppoe_flag: 24
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
auth svr: 119.6.23.78
pppoe_flag: 24
keep_alive2_flag: dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000

**Comment by madman43** [comment]
这是我在putty上拨通后运行python /usr/bin/drcom &后出来的提示
root@Hiwifi:~# python /usr/bin/drcom &
root@Hiwifi:~# [*]  auth svr: 119.6.23.78
[*]  pppoe_flag: 24
[*]  keep_alive2_flag: dc
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:0701100002000000857f761577054125a8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000007705412500620024857f76151e22a02d58a5220d0                                                    00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                    00000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:0701100002000000a27f761577054125a8a80000e659f16700000000dc020000
Traceback (most recent call last):
  File "/usr/bin/drcom", line 337, in <module>
    main()
  File "/usr/bin/drcom", line 333, in main
    pppoe.send(s)
  File "/usr/bin/drcom", line 197, in send
    data = self._make_heartbeat(sip=sip, challenge_seed=seed, first=True)
  File "/usr/bin/drcom", line 165, in _make_heartbeat
    crc, foo = gen_crc(challenge_seed, encrypt_mode)
  File "/usr/bin/drcom", line 75, in gen_crc
    foo = hashlib.new('md4', data).digest()
  File "/usr/lib/python2.7/hashlib.py", line 110, in __py_new
    return __get_builtin_constructor(name)(string)
  File "/usr/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md4

**Comment by mchome** [comment]
用 #82 底下的

**Comment by madman43** [comment]
#82 下面有两个啊，哪一个？

**Comment by mchome** [comment]
你就不能都测试麽，才两个

**Comment by madman43** [comment]
第一个测试出来是这样的
auth svr:119.6.23.78
pppoe_flag:24
keep_alive2_flag:dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000b016771570c3c294a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:07026000030000000000000070c3c29400620024b016771586a8422c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:070230000400200021aa108b000000004439d8ed77305c9c210b1c782ca404bfb0820060000000000000000000000000
[keep-alive2] send1
	packet:070028000b010f272f120000000000000000000000000000000000000000000000000000



第二个测试出来是这样的

auth svr:119.6.23.78
pppoe_flag:24
keep_alive2_flag:dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000b80c77157705426da8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:0702600003000000000000007705426d00620024b80c77151c1296e50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: received heartbeat response
	packet:070230000400200087846539000000004439d8ed77305c9ce08adda0246b043db0820060000000000000000000000000
[keep-alive2] send1
	packet:070028000b010f272f120000000000000000000000000000000000000000000000000000
auth svr:119.6.23.78
pppoe_flag:24
keep_alive2_flag:dc
open local port:61440
DEBUG MODE:True
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:0701100002000000e711771570c3c294a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:07026000030000000000000070c3c29400620024e71177152e4029b93c7e86500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000000312771570c3c294a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:07026000030000000000000070c3c2940062002403127715b2c8ac90283032bc0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000001e12771570c3c294a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:07026000030000000000000070c3c294006200241e127715a03602249a8597d20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000003b12771570c3c294a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:07026000030000000000000070c3c294006200243b12771581877ea6927073540000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry
pppoe: reset idx to 0x01
pppoe: send challenge request
	packet:0701080001000000
pppoe: received challenge response
	packet:07011000020000005712771570c3c294a8a80000e659f16700000000dc020000
pppoe: send heartbeat request
	packet:07026000030000000000000070c3c29400620024571277153d00e15a3a0ff5f20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
pppoe: heartbeat response failed, retry

**Comment by ly0** [comment]
第一个看上去是正常的

**Comment by madman43** [comment]
嗯，但是用默认的p版有时候会掉有时候不会，时间不定，这是怎么回事

**Comment by ly0** [comment]
掉的时候看一下日志。

**Comment by madman43** [comment]
默认的日志就是第四楼那个，我把IS_TEST=改成了True之后到现在没有掉过线了，日志也是第四楼的那些，

**Comment by madman43** [comment]
换成#82下面的第一个放到路由后，不能后台运行，自启不能启动，过一会就断忘了，rc.loal里面添加python  /usr/bin/com&也不行，这是怎么回事？
