### ISSUE TITLE
储存空间不足，无法保存日志文件，请问如何把日志记录功能屏蔽

### ISSUE THREAD

**Issue by dsjoin** [drcoms/drcom-generic#242]
如题，路由器空间过小，提示无法保存日志文件，导致无法正常拨号，请问如何在代码里面将日志记录功能屏蔽呢？，以下是路由器记录的日志：
```
Mon Sep  4 12:24:35 2017 user.emerg syslog: auth svr: 192.168.xxx.xx
Mon Sep  4 12:24:35 2017 user.emerg syslog: username: xxxxxxxxxxx
Mon Sep  4 12:24:35 2017 user.emerg syslog: password: xxxxxxx
Mon Sep  4 12:24:35 2017 user.emerg syslog: mac: 0x4cxxxxxxxx
Mon Sep  4 12:24:35 2017 user.emerg syslog: Traceback (most recent call last):
Mon Sep  4 12:24:35 2017 user.emerg syslog:   File "/bin/drcom", line 499, in <module>
Mon Sep  4 12:24:35 2017 user.emerg syslog:     main()
Mon Sep  4 12:24:35 2017 user.emerg syslog:   File "/bin/drcom", line 476, in main
Mon Sep  4 12:24:35 2017 user.emerg syslog:     log("auth svr: " + server + "\nusername: " + username + "\npassword: " + password + "\nmac: " + str(hex(mac))[:-1])
Mon Sep  4 12:24:35 2017 user.emerg syslog:   File "/bin/drcom", line 87, in log
Mon Sep  4 12:24:35 2017 user.emerg syslog:     with open(LOG_PATH,'a') as f:
Mon Sep  4 12:24:35 2017 user.emerg syslog: IOError: [Errno 28] No space left on device: 'drcom_client.log'
````

**Comment by mchome** [comment]
使用配置文件
