### ISSUE TITLE
长沙的联通dr5.2.1D

### ISSUE THREAD

**Issue by qiufeng666** [drcoms/drcom-generic#247]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>cd C:\Users\Administrator\Desktop\新建文件夹

C:\Users\Administrator\Desktop\新建文件夹>python latest-wired.py
Traceback (most recent call last):
  File "latest-wired.py", line 75, in <module>
    s.bind((bind_ip, 61440))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10048] 通常每个套接字地址(协议/网络地址/端口)

**Comment by qiufeng666** [comment]
OK解决了 我这是cmd命令 然后查进程吧61440端口给结束了
