### ISSUE TITLE
Python版，解决keep_alive1后，出现一分钟一掉线情况

### ISSUE THREAD

**Issue by luoanjun** [drcoms/drcom-generic#263]
发现是不停重新登陆，用的13号最后更新的latest-wired.py，现附日志如下
auth svr: 222.168.144.50
username: 2015302052333
password: 233333
mac: 0x902b34861c99
bind ip: 0.0.0.0
[challenge] recv 0202e7cd05ac0d000a000100f303e8f000000000ac106b020400a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202e7cd05ac0d000a000100f303e8f000000000ac106b020400a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010021eae1b9497a51c521ea2feb4bd902c65932303135333032303530313139000000000000000000000000000000000000000000000020017aca8dcf66c8ec7a502bced5dbf8d09d2f7037ffdfe201ac106b0d000000000000000000000000c50bcbde664ea22a0100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006c6b674eb5a2b020c50b2e04f0000902b34861c990000e913
[login] send 03010021eae1b9497a51c521ea2feb4bd902c65932303135333032303530313139000000000000000000000000000000000000000000000020017aca8dcf66c8ec7a502bced5dbf8d09d2f7037ffdfe201ac106b0d000000000000000000000000c50bcbde664ea22a0100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006c6b674eb5a2b020c50b2e04f0000902b34861c990000e913
[login] packet sent.
[login] recv timeout.
[challenge] recv 020297cd05ac0d000a000100f303e8f000000000ac106b020400a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020297cd05ac0d000a000100f303e8f000000000ac106b020400a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010021eae1b9497a51c521ea2feb4bd902c65932303135333032303530313139000000000000000000000000000000000000000000000020017aca8dcf66c8ec7a502bced5dbf8d09d2f7037ffdfe201ac106b0d000000000000000000000000c50bcbde664ea22a0100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006c6b674eb5a2b020c50b2e04f0000902b34861c990000e913
[login] send 03010021eae1b9497a51c521ea2feb4bd902c65932303135333032303530313139000000000000000000000000000000000000000000000020017aca8dcf66c8ec7a502bced5dbf8d09d2f7037ffdfe201ac106b0d000000000000000000000000c50bcbde664ea22a0100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006c6b674eb5a2b020c50b2e04f0000902b34861c990000e913
[login] packet sent.
[login] recv 0400000500000000000000000000000000ff00000000004472636fdea8903285dbac106b020172b00500030110
[login] loged in
[login] login sent
package_tail 4472636fdea8903285dbac106b020172
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200007e704503ac106b02a8a80000e659f16700000000dc020000
[keep_alive1] send ff000000000000007e704503e8371dbd1739d7b04472636fdea8903285dbac106b020172cd72
[keep-alive1]recv 070110000600cd727e704503ac106b02a8a80000e659f16700000000dc020000030000000000000002000000000000000000000000000000002f0d00ffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06dc022f12000000000000a8a80000e659f16700000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc3835a38a2ed0938a2ed0938a2ed096181fe093aa2ed0943bee10939a2ed09bbaab00932a2ed09bbbee3093aa2ed0957bde60939a2ed0957bde7093da2ed0957bde9093aa2ed0938a2ec0981a2ed090e84e9093ba2ed090e84e60930a2ed09ffa4eb0939a2ed09c782e9093ba2ed09
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070128000b02dc022f120000000000007e7045030000000000000000000000000000000000000000
[keep-alive2] send3 070228000b03dc022f120000000000007e7045030000000000000000ac106b0d0000000000000000
[keep-alive2] recv3 070228000b04dc022f120000000000007e7045030000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020100003d714503ac106b02a8a80000e659f16700000000dc020000
[keep_alive1] send ff000000000000003d714503ece28a03b891aa464472636fdea8903285dbac106b020172cd86
[keep-alive1] error
[keep_alive2] error raise Exception to main()
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\c.py", line 575, in main
    keep_alive2(SALT,package_tail,password,server)
  File "C:\Users\Administrator\Desktop\c.py", line 269, in keep_alive2
    keep_alive1(*args)
  File "C:\Users\Administrator\Desktop\c.py", line 511, in keep_alive1
    res, address = s.recvfrom(1024)
timeout: timed out

starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[challenge] recv 0202c2cd14ac0d000a000100f303e8f000000000ac106b020400a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202c2cd14ac0d000a000100f303e8f000000000ac106b020400a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010021f0d37961138df1e937514b38d2d6e5eb323031353330323035303131390000000000000000000000000000000000000000000000200160f84de70f1430aad7e3132a88180242d92e9b92718301ac106b0d000000000000000000000000964edab259837b460100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006162772aa11cd020c101bc36d0000902b34861c990000e913
[login] send 03010021f0d37961138df1e937514b38d2d6e5eb323031353330323035303131390000000000000000000000000000000000000000000000200160f84de70f1430aad7e3132a88180242d92e9b92718301ac106b0d000000000000000000000000964edab259837b460100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006162772aa11cd020c101bc36d0000902b34861c990000e913
[login] packet sent.
[login] recv timeout.
[challenge] recv 020211ce14ac0d000a000100f303e8f000000000ac106b020400a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020211ce14ac0d000a000100f303e8f000000000ac106b020400a8a80000e659f16700000000dc02000000800000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 03010021f0d37961138df1e937514b38d2d6e5eb323031353330323035303131390000000000000000000000000000000000000000000000200160f84de70f1430aad7e3132a88180242d92e9b92718301ac106b0d000000000000000000000000964edab259837b460100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006162772aa11cd020c101bc36d0000902b34861c990000e913
[login] send 03010021f0d37961138df1e937514b38d2d6e5eb323031353330323035303131390000000000000000000000000000000000000000000000200160f84de70f1430aad7e3132a88180242d92e9b92718301ac106b0d000000000000000000000000964edab259837b460100000000667579756d690000000000000000000000000000000000000000000000000000db95c237ac106b01000000000000000000000000940000000500000001000000280a00000200000057696e646f77732031300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021000006162772aa11cd020c101bc36d0000902b34861c990000e913
[login] packet sent.
[login] recv 0400000500000000000000000000000000ff00000000004472636fdea890329adbac106b020187b00500030110
[login] loged in
[login] login sent
package_tail 4472636fdea890329adbac106b020187
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 0701100002020000ce714503ac106b02a8a80000e659f16700000000dc020000
[keep_alive1] send ff00000000000000ce7145031e48d3a9afe52c234472636fdea890329adbac106b020187cd95
[keep-alive1]recv 070110000600cd95cf714503ac106b02a8a80000e659f16700000000dc020000030000000000000002000000000000000000000000000000002f0d00ffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06dc022f12000000000000a8a80000e659f16700000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc3835a38a2ed0938a2ed0938a2ed096181fe093aa2ed0943bee10939a2ed09bbaab00932a2ed09bbbee3093aa2ed0957bde60939a2ed0957bde7093da2ed0957bde9093aa2ed0938a2ec0981a2ed090e84e9093ba2ed090e84e60930a2ed09ffa4eb0939a2ed09c782e9093ba2ed09
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070128000b02dc022f12000000000000cf7145030000000000000000000000000000000000000000
[keep-alive2] send3 070228000b03dc022f12000000000000cf7145030000000000000000ac106b0d0000000000000000
[keep-alive2] recv3 070228000b04dc022f12000000000000cf7145030000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 07011000020200008e724503ac106b02a8a80000e659f16700000000dc020000
[keep_alive1] send ff000000000000008e7245038a8392efeaad85854472636fdea890329adbac106b020187cda9
[keep-alive1] error
[keep_alive2] error raise Exception to main()
[main] error something was wrong in keep_alives, do everything again
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\c.py", line 575, in main
    keep_alive2(SALT,package_tail,password,server)
  File "C:\Users\Administrator\Desktop\c.py", line 269, in keep_alive2
    keep_alive1(*args)
  File "C:\Users\Administrator\Desktop\c.py", line 511, in keep_alive1
    res, address = s.recvfrom(1024)
timeout: timed out

**Comment by ly0** [comment]
试过 18382c6 版本的吗
