### ISSUE TITLE
windows下运行latest-wired-python3.py测试出错闪退

### ISSUE THREAD

**Issue by InDimension** [drcoms/drcom-generic#264]
RESTART: C:\Users\msi\Downloads\drcom-generic-master\drcom-generic-master\latest-wired-python3.py 
auth svr: 172.30.255.2
username: （已经正确填写）
password: （已经正确填写）
mac: 0x448a5b6dc13
bind ip: 0.0.0.0
[challenge] recv 02029221929a1a0001000100f303e8f000000000ac1d2a21f000a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02029221929a1a0001000100f303e8f000000000ac1d2a21f000a8ac00004fe416c100000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
Traceback (most recent call last):
  File "C:\Users\msi\Downloads\drcom-generic-master\drcom-generic-master\latest-wired-python3.py", line 480, in <module>
    main()
  File "C:\Users\msi\Downloads\drcom-generic-master\drcom-generic-master\latest-wired-python3.py", line 470, in main
    package_tail = login(username, password, server)
  File "C:\Users\msi\Downloads\drcom-generic-master\drcom-generic-master\latest-wired-python3.py", line 382, in login
    packet = mkpkt(salt, usr, pwd, mac)
  File "C:\Users\msi\Downloads\drcom-generic-master\drcom-generic-master\latest-wired-python3.py", line 288, in mkpkt
    data += CONTROLCHECKSTATUS
TypeError: can't concat bytes to str
>>> 
不知道是不是我PY安装有误？抑或是哪里操作不当？

**Comment by NERD-k** [comment]
我也是近似的问题，我觉得这个代码有问题，还需要**调试**
我做了以下的修改
![conemu64_2017-10-14_21-00-34](https://user-images.githubusercontent.com/28424691/31575898-f0bbf30c-b122-11e7-8bed-cf998eb20481.png)
![conemu64_2017-10-14_21-03-13](https://user-images.githubusercontent.com/28424691/31575907-23c2fe26-b123-11e7-9be8-552400b8aeb8.png)
还会出现问题，我以前自己适配python3的时候最后也有这种问题：`self.count` *没有`len()`*

**Comment by mchome** [comment]
😄 改好了发pr吧

**Comment by NERD-k** [comment]
修改后的文件，有条件的测试一下，我最近事情比较多，这几天没时间搞这个了
[pppoe.txt](https://github.com/drcoms/drcom-generic/files/1419608/pppoe.txt)
