### ISSUE TITLE
电脑测试正常，路由运行失败

### ISSUE THREAD

**Issue by zimoua** [drcoms/drcom-generic#282]
> auth svr: 222.168.144.50
username: *****
password: *****
mac: 0x60f67775c38f
bind ip: 0.0.0.0
Traceback (most recent call last):
  File "/usr/bin/drcom", line 568, in <module>
    main()
  File "/usr/bin/drcom", line 558, in main
    package_tail = login(username, password, server)
  File "/usr/bin/drcom", line 422, in login
    salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
  File "/usr/bin/drcom", line 94, in challenge
    s.sendto("\x01\x02"+t+"\x09"+"\x00"*15, (svr, 61440))
socket.error: [Errno 128] Network is unreachable

**Comment by ly0** [comment]
网线没插吧

**Comment by zimoua** [comment]
插了  是不是要设置mac啥的

**Comment by ly0** [comment]
是的

**Comment by zimoua** [comment]
不能使用路由器原来的mac吗？

**Comment by ly0** [comment]
这个得问你们网管，有的地方IP和mac绑定的。

**Comment by zimoua** [comment]
请问在路由器上总是搁一段时间就掉了是怎么回事

**Comment by ly0** [comment]
发日志我才知道怎么回事

**Comment by OocoO** [comment]
...我也是。mac地址不知道设置什么。
