### ISSUE TITLE
景德镇陶瓷大学更新6.0.0(p)版后，所用py脚本（5.2.0p版本)不能使用了

### ISSUE THREAD

**Issue by 987428652** [drcoms/drcom-generic#294]
景德镇陶瓷大学更新6.0.0(p)版后，所用py脚本（5.2.0p版本)不能使用了,跑起来后显示如下
[*]  auth svr: 172.29.0.2
[*]  pppoe_flag: 2f
[*]  keep_alive2_flag: dc
[*]  open local port:61440
[*]  DEBUG MODE:False
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
[*]  pppoe: send heartbeat request
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
[*]  pppoe: send heartbeat request
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
[*]  pppoe: send heartbeat request
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
[*]  pppoe: send heartbeat request
^C[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
[*]  pppoe: send heartbeat request
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
Traceback (most recent call last):
  File "/usr/bin/drcom", line 451, in <module>
    main()
  File "/usr/bin/drcom", line 446, in main
    pppoe.send(s)
  File "/usr/bin/drcom", line 310, in send
    data = self._make_heartbeat(sip=sip, challenge_seed=seed, first=True)
  File "/usr/bin/drcom", line 281, in _make_heartbeat
    crc2 = (DrcomCRC32(data) * 19680126) & 0xFFFFFFFF
NameError: global name 'DrcomCRC32' is not defined
[6.0.0.zip](https://github.com/drcoms/drcom-generic/files/1825518/6.0.0.zip)

**Comment by mchome** [comment]
https://github.com/drcoms/drcom-generic/raw/master/latest-pppoe.py 试试这个

**Comment by 987428652** [comment]
谢谢大佬，可以用啦

**Comment by 987428652** [comment]
会断怎么办

**Comment by 987428652** [comment]
修改
server = '172.30.1.80'
pppoe_flag = '\x2a'
keep_alive2_flag = '\xdc'为
server = '172.29.0.2'
pppoe_flag = '\x2f'
keep_alive2_flag = '\xdc'后，不知道是否是跑动成功了（路由器内的py脚本修改 IS_TEST = True 为 IS_TEST = False后跑失败，只能True才成功），显示如下：
[*]  auth svr: 172.29.0.2
[*]  pppoe_flag: 2f
[*]  keep_alive2_flag: dc
[*]  open local port:61440
[*]  DEBUG MODE:True
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:07011000020000006cc353000a33f72da8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a33f72d0062002f6cc35300ca96cdc6000000000                                                                                                                                                             00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                                                                                                             00000000000000000000000000000000000000000000000
[*]  pppoe: received heartbeat response
        packet:0702300004002000b265b3b1000000004439d8edcae80004162282667f6904f6b                                                                                                                                                             0824000100000000000000000000000
[*]  [keep-alive2] send1
        packet:070028000b010f272f12000000000000000000000000000000000000000000000                                                                                                                                                             000000000000000
[*]  received message packet, dropped. message: You have witnessed too much...
[*]  [keep-alive2] recv file, resending..
[*]  [keep-alive2] send1
        packet:070128000b01dc022f12000000000000000000000000000000000000000000000                                                                                                                                                             000000000000000
[*]  [keep-alive2] recv1
        packet:070128000b02dc022f120000000000006dc353000000000000000000000000000                                                                                                                                                             000000000000000
[*]  [keep-alive2] send2
        packet:070128000b01dc022f12000000000000000000000000000000000000000000000                                                                                                                                                             000000000000000
[*]  [keep-alive2] recv2
        packet:070128000b02dc022f120000000000006dc353000000000000000000000000000                                                                                                                                                             000000000000000
[*]  [keep-alive2] send3
        packet:070228000b03dc022f120000000000006dc35300858da18363b3016b000000000                                                                                                                                                             000000000000000
[*]  [keep-alive2] recv3
        packet:070228000b04dc022f120000000000006dc353000000000000000000000000000                                                                                                                                                             000000000000000
[*]  [keep-alive2] keep-alive2 loop was in daemon.
[*]  [keep_alive2] send 3
        packet:070328000b01dc022f120000000000006dc353000000000000000000000000000                                                                                                                                                             000000000000000
[*]  [keep_alive2] recv
        packet:070328000b02dc022f120000000000006ec353000000000000000000000000000                                                                                                                                                             000000000000000
[*]  [keep_alive2] send 4
        packet:070428000b03dc022f120000000000006ec353008a80ac63d0c3f998000000000                                                                                                                                                             000000000000000
[*]  [keep_alive2] recv
        packet:070428000b04dc022f120000000000006ec353000000000000000000000000000                                                                                                                                                             000000000000000
[*]  pppoe: send challenge request
        packet:0702080001000000
[*]  pppoe: received challenge response
        packet:0702100002000000d2c353000a33f72da8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0703600003000000000000000a33f72d0063002fd2c353004a9eb8fb054b0f1d0                                                                                                                                                             00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                                                                                                             00000000000000000000000000000000000000000000000
[*]  pppoe: heartbeat response failed, retry
[*]  pppoe: reset idx to 0x01
[*]  pppoe: send challenge request
        packet:0701080001000000
[*]  pppoe: received challenge response
        packet:0701100002000000f0c353000a33f72da8a80000e659f16700000000dc020000
[*]  pppoe: send heartbeat request
        packet:0702600003000000000000000a33f72d0062002ff0c35300f2f13119000000000                                                                                                                                                             00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                                                                                                             00000000000000000000000000000000000000000000000

**Comment by 987428652** [comment]
大概一小时多，会断，这个脚本跑起来有时候显示响应错误

**Comment by luwensheng228** [comment]
你好，请问现在6.0.0P还可以跑吗
