### ISSUE TITLE
5.2.1（D）路由器运行几分钟掉线

### ISSUE THREAD

**Issue by 728528678** [drcoms/drcom-generic#299]
下面是部分的日志。学校是浙江工业大学，IP是自动获取，PC客户端连路由器是不限设备的。大神帮忙分析下是什么问题，路由器是小米青春版刷的pandorabox。
[keep_alive2] send 30 071e28000b03dc022f120000000000006adc501800000000000000000a0c0b820000000000000000
[keep_alive2] recv 071e28000b04dc022f120000000000006adc50180000000000000000000000000000000000000000
[keep_alive1] send ff1661ccb84369eef25fcf2b27f73772c40000004472636fc0a80601c5660a0c0b8201baa45e00000000
[keep-alive1] recv 070110000600a45e31dd50180a0c0b82a8a80000e659f16700000000dc0200002f010000da050000b8dc000063290000b439df02ffffffffffffffffffffffff
[keep_alive2] send 31 071f28000b01dc022f120000000000006adc50180000000000000000000000000000000000000000
[challenge] recv 0202e3a4ffbd350001000100f303e8f0000000000a0c0b82f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202e3a4ffbd350001000100f303e8f0000000000a0c0b82f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001ec77fe7acc72678e097f582f366568d7732313131373033333732000000000000000000000000000000000000000000000000000020035df1e3bee724ab4c7f36699266f16b00d12d165de211010a0c0b82000000000000000000000000382f611247bc844b010000000047494c4947494c49455945000000000000000000000000000000000000000000c0a8010100000000000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002600020c90dffe3400009a8e041220020000e913
[login] send 0301001ec77fe7acc72678e097f582f366568d7732313131373033333732000000000000000000000000000000000000000000000000000020035df1e3bee724ab4c7f36699266f16b00d12d165de211010a0c0b82000000000000000000000000382f611247bc844b010000000047494c4947494c49455945000000000000000000000000000000000000000000c0a8010100000000000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002600020c90dffe3400009a8e041220020000e913
[login] packet sent.
[login] recv 0400000500692900004c1ce002ffffffffff00000000004472636fc0a8060111670a0c0b820106b00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636fc0a8060111670a0c0b820106
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send ffc77fe7acc72678e097f582f366568d770000004472636fc0a8060111670a0c0b820106a46400000000
[keep-alive1] recv 070110000600a4646ddd50180a0c0b82a8a80000e659f16700000000dc020000030000000000000000000000692900004c1ce002ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06dc022f12000000000000a8a80000e659f16700000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc3835a38a2ed0938a2ed0938a2ed096181fe093aa2ed0943bee10939a2ed09bbaab00932a2ed09bbbee3093aa2ed0957bde60939a2ed0957bde7093da2ed0957bde9093aa2ed0938a2ec0981a2ed090e84e9093ba2ed090e84e60930a2ed09ffa4eb0939a2ed09c782e9093ba2ed09
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070128000b02dc022f120000000000006ddd50180000000000000000000000000000000000000000
[keep-alive2] send3 070228000b03dc022f120000000000006ddd501800000000000000000a0c0b820000000000000000
[keep-alive2] recv3 070228000b04dc022f120000000000006ddd50180000000000000000000000000000000000000000
[keep-alive2] keep-alive2 loop was in daemon.
[keep_alive1] send ffc77fe7acc72678e097f582f366568d770000004472636fc0a8060111670a0c0b820106a47800000000
[keep-alive1] recv 070110000600a47835de50180a0c0b82a8a80000e659f16700000000dc020000170000008801000073000000692900004c1ce002ffffffffffffffffffffffff
[keep_alive2] send 3 070328000b01dc022f120000000000006ddd50180000000000000000000000000000000000000000
[challenge] recv 020225a504be350001000100f303e8f0000000000a0c0b82f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
020225a504be350001000100f303e8f0000000000a0c0b82f000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001ef362bf42425bb0f630feff64d3e7ba4c323131313730333337320000000000000000000000000000000000000000000000000000200369ecbb50625949ba77afe0e7a416eb5e1f1e8ceab9e8010a0c0b8200000000000000000000000050ab35d255b509ed010000000047494c4947494c49455945000000000000000000000000000000000000000000c0a8010100000000000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002600020cd03a4ae700009a8e041220020000e913
[login] send 0301001ef362bf42425bb0f630feff64d3e7ba4c323131313730333337320000000000000000000000000000000000000000000000000000200369ecbb50625949ba77afe0e7a416eb5e1f1e8ceab9e8010a0c0b8200000000000000000000000050ab35d255b509ed010000000047494c4947494c49455945000000000000000000000000000000000000000000c0a8010100000000000000000000000000000000940000000500000001000000280a0000020000004e4f5445370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002600020cd03a4ae700009a8e041220020000e913
[login] packet sent.
[login] recv 04000005006a2900004d1ee002ffffffffff00000000004472636fc0a8060118670a0c0b82010db00501000100000000000000000000000110
[login] loged in
[login] login sent
package_tail 4472636fc0a8060118670a0c0b82010d
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1] send fff362bf42425bb0f630feff64d3e7ba4c0000004472636fc0a8060118670a0c0b82010da47e00000000
[keep-alive1] recv 070110000600a47e71de50180a0c0b82a8a80000e659f16700000000dc0200000300000000000000030000006a2900004d1ee002ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
Traceback (most recent call last):
  File "drcom", line 570, in <module>
    main()
  File "drcom", line 567, in main
    keep_alive2(SALT,package_tail,password,server)
  File "drcom", line 224, in keep_alive2
    data, address = s.recvfrom(1024)
socket.timeout: timed out

**Comment by ly0** [comment]
试着不要发送keep-alive1 试试

**Comment by 728528678** [comment]
注销掉main里的keep_alive1么？

**Comment by 728528678** [comment]
感谢，短时间没什么问题了，但是长时间还是出现掉线的情况，没有电脑记录的情况下能查看日志么？

**Comment by ly0** [comment]
长时间是多长？
建议在PC上跑到没问题再移植到路由上更好一些

**Comment by muamiao** [comment]
C语言版也遇到了这个问题，要怎样禁止发送keep_alive1呢？

**Comment by dadavinson** [comment]
已收到，谢谢|
