### ISSUE TITLE
[d版]由于空间所限，如何在Openwrt上仅安装python所需依赖

### ISSUE THREAD

**Issue by fengyuentau** [drcoms/drcom-generic#307]
路由器用得是斐讯k2(闪存大小好像是8MB)，已刷Breed和Openwrt 18.06.1。
刚刷完Openwrt，在Sysstem -> Software中，显示可用空间大小大概是4MB。
在安装完python-light和python-logging之后，大概剩下800KB的可用空间。
运行写好配置的`latest-wired.py`，先是报错：
```shell
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha512
```
后面接着是无限的：
```shell
[challenge] timeout, retrying...
```
从https://github.com/drcoms/drcom-generic/issues/111#issuecomment-251178055 获知还要安装`python-codecs`和`python-openssl`。但是`python-codecs`已经装不下了。
不知道还有没有可以删掉的不用的依赖库，或者所需依赖更少的drcom版本。

**Comment by fengyuentau** [comment]
使用openwrt-drcom
https://github.com/mchome/openwrt-dogcom/issues/6#issuecomment-420288616
