### ISSUE TITLE
5.2.1(d) 不定时keep-live1 challenge失败

### ISSUE THREAD

**Issue by Sailing-Young** [drcoms/drcom-generic#322]
[keep_alive2] send 3 070328000b01d8022f12000000000000f0d52b010000000000000000000000000000000000000000
[keep_alive2] recv 070328000b02d8022f12000000000000c3d62b010000000000000000000000000000000000000000
[keep_alive2] send 4 070428000b03d8022f12000000000000c3d62b010000000000000000ac1175630000000000000000
[keep_alive2] recv 070428000b04d8022f12000000000000ddd62b010000000000000000000000000000000000000000
[keep_alive1] send ff5d3f96e6dda179a55b671a395b709cb40000004472636f0a0101035daeac1175630162c0eb00000000
[challenge] recv 070110000600c0ebb2d72b01ac117563a8a20000294d4d3f00000000d802000034000000ac0100004935000060030000d39e2700ffffffffffffffffffffffff
[DEBUG] challenge:
070110000600c0ebb2d72b01ac117563a8a20000294d4d3f00000000d802000034000000ac0100004935000060030000d39e2700ffffffffffffffffffffffff
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\drcom\fwyy.py", line 568, in <module>
    main()
  File "C:\Users\Administrator\Downloads\drcom\fwyy.py", line 558, in main
    package_tail = login(username, password, server)
  File "C:\Users\Administrator\Downloads\drcom\fwyy.py", line 422, in login
    salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
  File "C:\Users\Administrator\Downloads\drcom\fwyy.py", line 108, in challenge
    raise ChallengeException
__main__.ChallengeException

**Comment by Sailing-Young** [comment]
我尝试了keep_alive1_mod = True 不知道行不行

**Comment by Sailing-Young** [comment]
尝试一段试试看

**Comment by Sailing-Young** [comment]
不行 注释掉了keep_alive1

**Comment by Sailing-Young** [comment]
`def main():
    if not IS_TEST:
        daemon()
        execfile(CONF, globals())
    log("auth svr: " + server + "\nusername: " + username + "\npassword: " + password + "\nmac: " + str(hex(mac))[:-1])
    log("bind ip: " + bind_ip)
    while True:
        try:
            package_tail = login(username, password, server)
        except LoginException:
            continue
        log('package_tail',package_tail.encode('hex'))
        #keep_alive1 is fucking bullshit!
        empty_socket_buffer()
        #keep_alive1(SALT,package_tail,password,server)
        keep_alive2(SALT,package_tail,password,server)`
注释掉main里的keep_alive1后目前一切正常
只留下keep_alive2里的keep_alive1

**Comment by lcyzgdy** [comment]
我尝试了注释掉main里的keep_alive1，同时令keep_alive1_mod = True，但仍然出现这个错误。
`[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 4d384cc9bcecb2e2b7a2cfd6203120b4ce2c203120b4cebaf3b4a6c0ed202c20d6d5b6cb203e20322c20
[challenge] recv 078f1000020000005f632f03ac180cbca8a80000e659f16700000000dc020000
[DEBUG] challenge:
078f1000020000005f632f03ac180cbca8a80000e659f16700000000dc020000
Traceback (most recent call last):
  File "drcom_new.py", line 573, in <module>
    main()
  File "drcom_new.py", line 563, in main
    package_tail = login(username, password, server)
  File "drcom_new.py", line 427, in login
    salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
  File "drcom_new.py", line 113, in challenge
    raise ChallengeException
__main__.ChallengeException`
这里我用的最新的drcom-generic/latest-wired.py文件，请问有没有解决方案？

**Comment by muamiao** [comment]
C语言版要怎么弄呢？

**Comment by Zaomengzhe** [comment]
同求C语言版本怎么弄呢？
