### ISSUE TITLE
6.0.0 D版 登录报错 西南石油大学（南充校区）

### ISSUE THREAD

**Issue by wdljt** [drcoms/drcom-generic#362]
# Log
auth svr: 10.10.0.4
username: 19161056787
password: ******
mac: 0x940100000600
bind ip: 0.0.0.0
[challenge] recv 0202fe806c730e0000000100f303e8f0000000000a1d114ef000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
0202fe806c730e0000000100f303e8f0000000000a1d114ef000a8a80000e659f16700000000dc02000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001fe696d38abcef8f33cb033f21cc47bd5f31393136313035363738370000000000000000000000000000000000000000000000000020047297d38abaef95e921ff7ad6c27834e5fb4a8a213a82010a1d114e00000000000000000000000013de2f0f146b6c510100000000667579756d690000000000000000000000000000000000000000000000000000da06c88b0a0a0105000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002c00020c6090375d00009401000006000000e913
[login] send 0301001fe696d38abcef8f33cb033f21cc47bd5f31393136313035363738370000000000000000000000000000000000000000000000000020047297d38abaef95e921ff7ad6c27834e5fb4a8a213a82010a1d114e00000000000000000000000013de2f0f146b6c510100000000667579756d690000000000000000000000000000000000000000000000000000da06c88b0a0a0105000000000000000000000000940000000500000001000000280a00000200000057696e646f7773203130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002c00020c6090375d00009401000006000000e913
[login] packet sent.
[login] recv 04000005006a000000c5c38600ffffffffff00000000004472636f0a0a00048dbc0a1d114e01bfb00500030110
[login] loged in
[login] login sent
package_tail 4472636f0a0a00048dbc0a1d114e01bf
starting to empty socket buffer
exception in empty_socket_buffer
emptyed
[keep_alive1_challenge] keep_alive1_challenge packet sent.
[keep_alive1_challenge] recv 073f1000020000002fb2a7190a1d114ea8a80000e659f16700000000dc020000
[keep_alive1] send ff000000000000002fb2a719af9925c6944b776b4472636f0a0a00048dbc0a1d114e01bf80be
[keep-alive1]recv 07011000060080be30b2a7190a1d114ea8a80000e659f16700000000dc0200000300000000000000000000006a000000c5c38600ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06dc022f12000000000000a8a80000e659f16700000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc3835a38a2ed0938a2ed0938a2ed096181fe093aa2ed0943bee10939a2ed09bbaab00932a2ed09bbbee3093aa2ed0957bde60939a2ed0957bde7093da2ed0957bde9093aa2ed0938a2ec0981a2ed090e84e9093ba2ed090e84e60930a2ed09ffa4eb0939a2ed09c782e9093ba2ed09
[keep-alive2] recv file, resending..
[keep-alive2] send2 070128000b01db022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070110010b06dc022f12000000000000a8a80000e659f16700000000dc0200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a24000000000000007cc3835a38a2ed0938a2ed0938a2ed096181fe093aa2ed0943bee10939a2ed09bbaab00932a2ed09bbbee3093aa2ed0957bde60939a2ed0957bde7093da2ed0957bde9093aa2ed0938a2ec0981a2ed090e84e9093ba2ed090e84e60930a2ed09ffa4eb0939a2ed09c782e9093ba2ed09
[keep-alive2] send3 070228000b03db022f12000000000000a8a8000000000000000000000a1d114e0000000000000000
Traceback (most recent call last):
  File "C:\Users\wdljt\Desktop\drcom-generic-master\latest-wired.py", line 568, in <module>
    main()
  File "C:\Users\wdljt\Desktop\drcom-generic-master\latest-wired.py", line 565, in main
    keep_alive2(SALT,package_tail,password,server)
  File "C:\Users\wdljt\Desktop\drcom-generic-master\latest-wired.py", line 255, in keep_alive2
    data, address = s.recvfrom(1024)
socket.timeout: timed out

# Config
server = '10.10.0.4'
username = '19161056787'
password = '******'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x04'
host_ip = '10.29.17.78'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '218.6.200.139'
dhcp_server = '10.10.1.5'
AUTH_VERSION = '\x2c\x00'
mac = 0x940100000600
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdb\x02'
ror_version = True

**Comment by WesternLi** [comment]
同西柚南充
这是我用的配置，是可以使用的

server = '10.10.0.3'
username = 'XYNCSYD1774672****'
password = '******'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x08'
host_ip = '10.28.211.155'
IPDOG = '\x01'
host_name = 'fuyumi'
PRIMARY_DNS = '172.16.245.2'
dhcp_server = '10.10.1.5'
AUTH_VERSION = '\x2c\x00'
mac = 0x940100000600
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = True

**Comment by wdljt** [comment]
我后来发现是双IP认证.4和.3都有认证系统，然后认证完了是.4可以断开.3不能断，其实折腾的差不多了，只是忘关issue了，感谢分享！
