### ISSUE TITLE
电脑测试正常，路由器上运行出错。[Errno 128] Network is unreachable

### ISSUE THREAD

**Issue by tangmifa** [drcoms/drcom-generic#55]
经测试，电脑测试正常，在路由器中运行出错。

> [Errno 128] Network is unreachable

输出如下。

```
auth svr:10.1.1.254
username:xxx
password:xxx
mac:0xd73c020cf08dL
0.0.0.0
Traceback (most recent call last):
  File "/usr/bin/drcom.py", line 384, in <module>
    main()
  File "/usr/bin/drcom.py", line 375, in main
    package_tail = login(username, password, server)
  File "/usr/bin/drcom.py", line 302, in login
    salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
  File "/usr/bin/drcom.py", line 88, in challenge
    s.sendto("\x01\x02"+t+"\x09"+"\x00"*15, (svr, 61440))
socket.error: [Errno 128] Network is unreachable
```
附/usr/bin/drcom_client.log
```
auth svr:10.1.1.254
username:xxx
password:xxx
mac:0xd73c020cf08dL
0.0.0.0
```

附配置文件/etc/drcom.conf

```
server = '10.1.1.254'
username='xxx'
password='xxx'
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x03'
host_ip = '172.23.134.15'
IPDOG = '\x01'
host_name = 'DRCOMFUCKER'
PRIMARY_DNS = '218.196.40.9'
dhcp_server = '218.196.40.8'
AUTH_VERSION = '\x27\x00'
mac = 0xd73c020cf08d
host_os = 'WINDIAOS'
KEEP_ALIVE_VERSION = '\xd8\x02'
```

望指点迷津

**Comment by mchome** [comment]
获取到了ip吗，能ping通网关吗？

**Comment by tangmifa** [comment]
路由器不能获取ip，ping不通网关。

**Comment by mchome** [comment]
想办法获取到

**Comment by tangmifa** [comment]
我加油

**Comment by zytomorrow** [comment]
同样出现这情况，无法Ping通网关，请问你是怎么解决的
