### ISSUE TITLE
5.20P版在win下已测试成功，在ubuntu下执行latest-pppoe脚本时出现错误

### ISSUE THREAD

**Issue by yuyuen72** [drcoms/drcom-generic#6]
拨号已成功，只是

yy@yy-upc:~$ python2 latest-pppoe.py 
[*]  open local port:61440
[*]  DEBUG MODE:False
[*]  pppoe: send challenge request
[*]  pppoe: received challenge response
[*]  pppoe: send heartbeat request
[*]  pppoe: received heartbeat response
[*]  [keep-alive2] send1
Traceback (most recent call last):
  File "latest-pppoe.py", line 273, in <module>
    main()
  File "latest-pppoe.py", line 270, in main
    keep_alive2(s, pppoe)
  File "latest-pppoe.py", line 198, in keep_alive2
    data, address = s.recvfrom(1024)
  File "latest-pppoe.py", line 79, in recvfrom
    return self.recv()
  File "latest-pppoe.py", line 68, in recv
    log('received message packet, dropped. message:' + gbk2utf8(data[4:]))
  File "latest-pppoe.py", line 46, in gbk2utf8
    return string.decode('gb2312').encode().decode()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-10: ordinal not in range(128)
yy@yy-upc:~$ 

不知问题出在那里？

**Comment by yuyuen72** [comment]
已解决，第46行判断操作系统是否为windows的if语句去掉，全当windows即可
